resources:
- service.yaml
- deployment.yaml

# not supported by OLM :/ Created in code for now
#- consoleplugin.yaml

generatorOptions:
  disableNameSuffixHash: true

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: console-plugin
  newName: quay.io/medik8s/node-remediation-console
  newTag: latest

# copied from default after removing it from there
namePrefix: node-healthcheck-

commonLabels:
  app.kubernetes.io/name: node-healthcheck-operator
