name: Publish Container Images
on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  push_to_registry:
    name: Build and push images to quay.io/medik8s
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Log in to Quay.io
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
          registry: quay.io

      - name: Build and push CSV 0.0.1 + latest images, for pushes
        if: ${{ $GITHUB_REF_TYPE != 'tag' }}
        run: make docker-build bundle bundle-build docker-push bundle-push

      - name: Build and push versioned CSV and images, for tags
        if: ${{ $GITHUB_REF_TYPE == 'tag' }}
        # remove leading 'v' from tag!
        run: export VERSION=$(echo $GITHUB_REF_NAME | sed 's/v//') && make docker-build bundle bundle-build docker-push bundle-push
